### ISSUE TITLE
TZ isn't used

### ISSUE THREAD

**Issue by tik-stbuehler** [librenms/docker#49]
The `TZ` [Environment variable](https://github.com/librenms/docker/blob/master/doc/docker/environment-variables.md) isn't used as far as I can tell; it probably should be used to configure the php timezone.

LibreNMS config validation says:

```
Fail: Time between this server and the mysql database is off Mysql time 2019-11-29 08:39:53 PHP time 2019-11-29 07:39:53
```

The Mysql server uses Europe/Berlin (run in a "standard" debian environment, not docker), and I configured `TZ=Europe/Berlin` for LibreNMS, but it obviously uses UTC.

**Comment by crazy-max** [comment]
Hi @tik-stbuehler, `TZ` is actually used in the container itself but not through PHP. I will push a fix asap, thanks for your input.

**Comment by crazy-max** [comment]
@tik-stbuehler Should be fixed now

**Comment by tik-stbuehler** [comment]
Hi @crazy-max!

Thanks for the quick reaction, very impressive :)

Sadly the config validator still isn't happy:

```
Fail: You have a different system timezone (UTC) than the php configured timezone (CET)
Fix:
Please correct either your system timezone or your timezone set in php.ini. 
```

No idea whether this leads to actual problems / is visible somewhere.

As far as I can tell the problem is the `TZ` environment variable not getting passed to php-fpm (supervise only sets `PATH` and clears everything else). To set a default timezone something like this should do (from https://wiki.archlinux.org/index.php/System_time):

```
ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime
```

Setting the symlink manually fixes the issue for me.

**Comment by crazy-max** [comment]
Can you show me your compose file and env file (without sensitive data) please ?

**Comment by tik-stbuehler** [comment]
I'm using direct spawning through sytemd services; the "UI" (web frontend) one looks like this:

```
# /etc/systemd/system/librenms-ui.service
[Unit]
Description=LibreNMS UI docker container
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/bin/docker stop %n
ExecStartPre=-/usr/bin/docker rm %n
ExecStartPre=/usr/bin/docker pull librenms/librenms:1.58.1
ExecStart=/usr/bin/docker run --rm --name %n \
  --env-file=/etc/librenms-docker.env \
  -v /var/lib/librenms-data:/data \
  -v /var/lib/librenms-data/monitoring-plugins:/opt/librenms/html/plugins \
  -p 127.0.0.1:8000:8000 \
  librenms/librenms:1.58.1

[Install]
WantedBy=multi-user.target
```

```
# /etc/librenms-docker.env
TZ=Europe/Berlin
PUID=955
PGID=955
DB_HOST=[...]
DB_NAME=librenms
DB_USER=librenms
DB_PASSWORD=...

LIBRENMS_DISTRIBUTED_POLLER_ENABLE=true
MEMCACHED_HOST=librenms-rrd.[...]
MEMCACHED_PORT=11211
RRDCACHED_HOST=librenms-rrd.[...]

LIBRENMS_CRON_BILLING_ENABLE=false
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=false
```

The pollers systemd services use additional environment variables:
```
  -e LIBRENMS_DISTRIBUTED_POLLER_NAME=%H \
  -e SIDECAR_CRON=1 \
```

and (`true` or `false` depending whether it's the first poller or not):
```
  -e LIBRENMS_CRON_DISCOVERY_ENABLE=true \
  -e LIBRENMS_CRON_ALERTS_ENABLE=true \
```

rrdcached, memcached and mysql (maria) db are running on normal debian systems without docker.

**Comment by crazy-max** [comment]
Can you give me the output of

`docker exec -it librenms-ui date`
`docker exec -it librenms-ui php -r 'echo date("Y-m-d H:i:s");`

**Comment by tik-stbuehler** [comment]
Sure:
```
root@librenms:~# docker exec -it librenms-ui.service date
Thu Dec  5 08:52:27 CET 2019
root@librenms:~# docker exec -it librenms-ui.service php -r 'echo date("Y-m-d H:i:s\n");'
2019-12-05 08:52:29
```

This is no surprise giving `TZ` is in the environment here:
```
root@librenms:~# docker exec -it librenms-ui.service env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=74e534d4f54c
TERM=xterm
TZ=Europe/Berlin
PUID=955
PGID=955
DB_HOST=[...]
DB_NAME=librenms
DB_USER=librenms
DB_PASSWORD=[...]
LIBRENMS_DISTRIBUTED_POLLER_ENABLE=true
MEMCACHED_HOST=librenms-rrd.[...]
MEMCACHED_PORT=11211
RRDCACHED_HOST=librenms-rrd.[...]
LIBRENMS_CRON_BILLING_ENABLE=false
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=false
LIBRENMS_VERSION=1.58.1
LIBRENMS_PATH=/opt/librenms
LIBRENMS_DOCKER=1
S6_BEHAVIOUR_IF_STAGE2_FAILS=2
HOME=/root
```

But `s6-svscan` and its child processes start with a clean environment (no `TZ`, only `PATH`):
```
root@librenms:~# ps aufx
[...]
root       848  0.1  2.1 1074412 87668 ?       Ssl  Dez03   3:59 /usr/sbin/dockerd -H fd://
root      1127  0.1  0.9 1025892 37428 ?       Ssl  Dez03   3:19  \_ docker-containerd --config /var/run/docker/containerd/containerd.toml --log-level info
root     29035  0.0  0.2 922296 11516 ?        Sl   Dez03   0:34  |   \_ docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/74e534d4f54c6dbd147719b02a3d79c68188a54f0fba77e46ff8cdc277bc13ce -address /var/run/docker/containerd/containerd.sock -containerd-binary /usr/bin/docker-containerd -runtime-root /var/run/docker/runtime-runc
root     29055  0.0  0.0    200     4 ?        Ss   Dez03   0:00  |       \_ s6-svscan -t0 /var/run/s6/services
root     29120  0.0  0.0    204     4 ?        S    Dez03   0:00  |           \_ s6-supervise s6-fdholderd
root     29457  0.0  0.0    204     4 ?        S    Dez03   0:00  |           \_ s6-supervise nginx
librenms 29463  0.0  0.1   5800  4400 ?        Ss   Dez03   0:00  |           |   \_ nginx: master process nginx -g daemon off;
librenms 29470  0.0  0.1  12492  4396 ?        Sl   Dez03   0:05  |           |       \_ nginx: worker process
librenms 29471  0.0  0.1  13188  4284 ?        Sl   Dez03   1:41  |           |       \_ nginx: worker process
root     29458  0.0  0.0    204     4 ?        S    Dez03   0:00  |           \_ s6-supervise snmpd
root     29461  0.0  0.1   9632  7084 ?        Ss   Dez03   0:30  |           |   \_ /usr/sbin/snmpd -f -c /etc/snmp/snmpd.conf
root     29459  0.0  0.0    204     4 ?        S    Dez03   0:00  |           \_ s6-supervise php-fpm
librenms 29462  0.0  0.6 164476 25196 ?        Ss   Dez03   0:07  |               \_ php-fpm: master process (/etc/php7/php-fpm.conf)
librenms 14057  0.3  0.9 171712 40396 ?        S    07:43   0:14  |                   \_ php-fpm: pool www
librenms 17834  0.3  0.9 171712 40404 ?        S    07:59   0:11  |                   \_ php-fpm: pool www
librenms 19035  0.3  1.0 171760 40444 ?        S    08:04   0:11  |                   \_ php-fpm: pool www
librenms 23245  0.3  0.9 171708 40396 ?        S    08:19   0:08  |                   \_ php-fpm: pool www
librenms 28522  0.3  0.9 171700 40080 ?        S    08:39   0:03  |                   \_ php-fpm: pool www
librenms 31027  0.3  0.9 171644 39668 ?        S    08:49   0:01  |                   \_ php-fpm: pool www
root     29027  0.0  0.1 770880  7056 ?        Sl   Dez03   0:29  \_ /usr/sbin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 8000 -container-ip 192.168.131.1 -container-port 8000
[...]
root@librenms:~# strings /proc/29055/environ 
PATH=/usr/bin:/usr/sbin:/bin:/sbin
```

And without `TZ` it looks like this:
```
root@librenms:~# docker exec -it librenms-ui.service sh -c 'unset TZ; date'
Thu Dec  5 07:57:09 UTC 2019
root@librenms:~# docker exec -it librenms-ui.service sh -c "unset TZ; php -r 'echo date(\"Y-m-d H:i:s\n\");'"
2019-12-05 08:57:55
```

But if I add the `/etc/localtime` symlink it works:
```
root@librenms:~# docker exec -it librenms-ui.service ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
root@librenms:~# docker exec -it librenms-ui.service sh -c 'unset TZ; date'
Thu Dec  5 09:00:32 CET 2019
root@librenms:~# docker exec -it librenms-ui.service sh -c "unset TZ; php -r 'echo date(\"Y-m-d H:i:s\n\");'"
2019-12-05 09:00:59
```

**Comment by crazy-max** [comment]
> But s6-svscan and its child processes start with a clean environment (no TZ, only PATH):

No, [container environment variables are available for s6 services](https://github.com/librenms/docker/blob/master/rootfs/etc/cont-init.d/04-svc-main.sh#L68-L92) through [`with-contenv` helper](https://github.com/just-containers/s6-overlay/#container-environment).

> But if I add the /etc/localtime symlink it works:

No need to create a symlink, [`tzdata`](https://pkgs.alpinelinux.org/package/v3.10/main/x86_64/tzdata) package takes care of that through [`TZ` environment variable](https://data.iana.org/time-zones/tz-link.html). This is the most elegant way to set timezone. And also create this symlink require root permissions.

**Comment by tik-stbuehler** [comment]
Well... ok, so `with-contenv` works around the problem that `s6` cleans the environment.  But `php-fpm` cleans it again ([`clear_env` in a pool](https://www.php.net/manual/en/install.fpm.configuration.php#clear-env) defaults to yes):

- in the container: `echo '<?php header("content-type: text/plain; charset=utf-8"); system("env");' > /opt/librenms/html/info.php`
- `curl https://librenms/info.php`:

      USER=librenms
      SHLVL=1
      HOME=/opt/librenms
      PWD=/opt/librenms/html

Setting the symlink in `04-svc-main.sh` should be easy, as it runs as root.

As an alternative one might put `putenv("TZ=Europe/Berlin");` in librenms config php files.

Disabling `clear_env` might have lots of side effects.

**Comment by crazy-max** [comment]
@tik-stbuehler 

> But php-fpm cleans it again (clear_env in a pool defaults to yes):

Ah good catch! I will bring back symlink creation through cont init.

**Comment by crazy-max** [comment]
@tik-stbuehler Should be ok now

**Comment by tik-stbuehler** [comment]
Thanks for your hard work!

But... it seems php doesn't use `/etc/localtime` (nor `TZ`): [date_default_timezone_get()](https://www.php.net/manual/en/function.date-default-timezone-get.php) - and as now the Dockerfile doesn't uncomment `date.timezone` anymore, `03-config.sh` changes `php.ini` only to `;date.timezone = Europe/Berlin`.

Perhaps use `sed -i "s|;*date\.timezone.*|date\.timezone = ${TZ}|g" /etc/php7/php.ini` in `03-config.sh`?

**Comment by crazy-max** [comment]
Good catch AGAIN :sweat_smile:

**Comment by crazy-max** [comment]
@tik-stbuehler Should be FINALLY fine :sweat_smile:

**Comment by tik-stbuehler** [comment]
Confirmed, all green now :) Thanks!
